#!/usr/bin/env ruby

require 'celluloid'
require 'cooperator'
require 'nokogiri'
require 'open-uri'

module Hoard
  class Page
    include Celluloid

    def process(number, description, location, selector, attribute, destination)
      sleep rand

      html = Nokogiri::HTML open location

      source = html.css(selector).first[attribute]

      FUTURES << IMAGES.future.grab(source, destination, description)

      description
    end
  end

  class Image
    include Celluloid

    def grab(source, destination, description)
      `curl -sS -o #{destination.inspect} #{source.inspect}`

      puts description

      description
    end
  end

  def self.MangaFox(context = {})
    MangaFox::GrabManga.perform context
  end

  module MangaFox
    class GrabManga
      prepend Cooperator

      def perform
        cooperate GetTitleAndChapters,
                  LimitChapters,
                  GrabChapters
      end
    end

    class GetTitleAndChapters
      prepend Cooperator

      def perform
        html = Nokogiri::HTML open "http://mangafox.me/manga/#{context.name}/"

        title! html
        chapters! html
      end

      private

      def title!(html)
        title = html.title
        title.gsub!(/ Manga .*$/, '')

        context.title = title
      end

      def chapters!(html)
        chapters = {}

        matches = html.css 'a.tips'
        matches.reverse.each do |match|
          href = match['href']

          location = href.gsub(/\/1\.html$/, '')
          volume, chapter = /\/v(.*?)\/c(.*?)\/1\.html$/.match(href) { |m| [m[1], m[2]] }
          index = [volume, chapter].join '-'

          chapters[index] = {
            index: index,
            chapter: chapter,
            volume: volume,
            location: location
          }
        end

        context.chapters = chapters
      end
    end

    class LimitChapters
      prepend Cooperator

      def perform
        context.chapters.select! do |index, chapter|
          context.index.match index
        end
      end
    end

    class GrabChapters
      prepend Cooperator

      def selector
        'img#image'
      end

      def attribute
        'src'
      end

      def perform
        context.chapters.each do |index, chapter|
          html = Nokogiri::HTML open "#{chapter[:location]}/1.html"

          title = html.css("meta[property='og:description']").first['content'] rescue nil
          if title
            title.gsub! /(.*?: )/, ''
          end

          source = html.css(selector).first[attribute]

          directory = File.join 'Manga', context.title, [index, title].compact.join(' ')
          prepare! directory

          html.css('.r.m .l select').first.css('option').each do |option|
            page = "%03d" % option['value']

            next if page == '000'

            description = [
              context.title,
              index,
              page,
              title
            ].compact.join ' - '

            location = "#{chapter[:location]}/#{page}.html"
            destination = File.join directory, "#{page}.jpg"

            FUTURES << PAGES.future.process(page, description, location, selector, attribute, destination)
          end
        end
      end

      private

      def prepare!(directory)
        FileUtils.mkdir_p directory
      end
    end
  end
end

PAGES = Hoard::Page.pool size: 2
IMAGES = Hoard::Image.pool size: 6
FUTURES = []

name = ARGV[0]
index = Regexp.new ARGV[1]

Hoard.MangaFox name: name, index: index

FUTURES.each do |future|
  future.value
end
